[package]
name = "idf-im-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.37.0", features=["full"]}
idf-im-lib = { git = "https://github.com/espressif/idf-im-lib.git", rev="ab47231634cd0ff1c77cce633100008a0fd36eb4" }
clap = {version = "4.5", features = ["cargo", "derive"]}
crossterm = "0.27.0"
dialoguer = "0.11.0"
byte-unit = "5.1.4"
indicatif = "0.17.8"
ratatui-splash-screen = "0.1.3"
rfd = "0.14.1"
walkdir = "2.5.0"
console = "0.15.8"
config = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
git2 = "0.19.0"
log = "0.4.21"
simple_logger = "5.0.0"
